import Head from "next/head";
import { css } from "@emotion/css";
import ShopList from "../component/ShopList/ShopList";
import ShopFilter from "../component/ShopFilter/ShopFilter";

export default function Home() {
  return (
    <div className={container}>
      <Head>
        <title>IVTN</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={header}>
        <p className={title}>IVTN</p>
      </div>
      <div className={bodyBox}>
        <ShopFilter />
        <ShopList />
      </div>
    </div>
  );
}

const container = css`
  height: 100%;
`;

const header = css`
  height: 65px;
  font-family: "campton", "Apple SD Gothic Neo", NanumBarunGothic,
    "나눔바른고딕", Malgun Gothic, "맑은 고딕", dotum, sans-serif;
  color: black;
  padding: 21px 10px;
  text-align: center;
  background-color: #fff;
  border-bottom: 1px solid #d4d4d4;
`;

const title = css`
  font-size: 20px;
  height: 25px;
  line-height: 25px;
  font-weight: 800;
`;

const bodyBox = css`
  margin: 0 auto;
  position: relative;
`;
